baseurl = "http://www.oslet.net/"
title = "let's make os"
languageCode = "en-us"
disqusShortname = "oslet"
copyright = "Copyright (c) 2016, eutler lee; all rights reserved."
MetaDataFormat = "yaml"

[author]
    name = "Eutler Lee"

[indexes]
    tag = "tags"
    topic = "topics"

